# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tf_detection/protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tf_detection.protos.faster_rcnn_pb2
import tf_detection.protos.ssd_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tf_detection/protos/model.proto',
  package='tf_detection.protos',
  serialized_pb=_b('\n\x1ftf_detection/protos/model.proto\x12\x13tf_detection.protos\x1a%tf_detection/protos/faster_rcnn.proto\x1a\x1dtf_detection/protos/ssd.proto\"z\n\x0e\x44\x65tectionModel\x12\x36\n\x0b\x66\x61ster_rcnn\x18\x01 \x01(\x0b\x32\x1f.tf_detection.protos.FasterRcnnH\x00\x12\'\n\x03ssd\x18\x02 \x01(\x0b\x32\x18.tf_detection.protos.SsdH\x00\x42\x07\n\x05model')
  ,
  dependencies=[tf_detection.protos.faster_rcnn_pb2.DESCRIPTOR,tf_detection.protos.ssd_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DETECTIONMODEL = _descriptor.Descriptor(
  name='DetectionModel',
  full_name='tf_detection.protos.DetectionModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='faster_rcnn', full_name='tf_detection.protos.DetectionModel.faster_rcnn', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssd', full_name='tf_detection.protos.DetectionModel.ssd', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='model', full_name='tf_detection.protos.DetectionModel.model',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=126,
  serialized_end=248,
)

_DETECTIONMODEL.fields_by_name['faster_rcnn'].message_type = tf_detection.protos.faster_rcnn_pb2._FASTERRCNN
_DETECTIONMODEL.fields_by_name['ssd'].message_type = tf_detection.protos.ssd_pb2._SSD
_DETECTIONMODEL.oneofs_by_name['model'].fields.append(
  _DETECTIONMODEL.fields_by_name['faster_rcnn'])
_DETECTIONMODEL.fields_by_name['faster_rcnn'].containing_oneof = _DETECTIONMODEL.oneofs_by_name['model']
_DETECTIONMODEL.oneofs_by_name['model'].fields.append(
  _DETECTIONMODEL.fields_by_name['ssd'])
_DETECTIONMODEL.fields_by_name['ssd'].containing_oneof = _DETECTIONMODEL.oneofs_by_name['model']
DESCRIPTOR.message_types_by_name['DetectionModel'] = _DETECTIONMODEL

DetectionModel = _reflection.GeneratedProtocolMessageType('DetectionModel', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONMODEL,
  __module__ = 'tf_detection.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:tf_detection.protos.DetectionModel)
  ))
_sym_db.RegisterMessage(DetectionModel)


# @@protoc_insertion_point(module_scope)
